#%RAML 1.0 Trait
  usage: Apply this trait to client_id identification 
  headers:
    client_id:
      type: string
      description: To authenticate system API
      required: false
    client_secret:
      type: string
      description: To authenticate system API
      required: false
