#%RAML 1.0 Trait
  usage : Apply this trait to maintain transaction id to track transactions
  headers:
    x-correlation-id:
        type: string
        description: Transaction id to maintian over API's
        required: false