#%RAML 1.0 Trait
  usage : Apply this trait to maintain transaction id to track transactions
  headers:
    x-transaction-id:
      type: string
      required: false
      description: To maintion transactions over APIs